In [1]:
import numpy as np

class Perceptron:

    def __init__(self, input_size, lr=0.2, epochs=4):
        self.W = np.array([0.3, -0.2], dtype=float)
        self.lr = lr
        self.epochs = epochs

    def activation_fn(self, x):
        if x >= 0:
            return 1
        else:
            return 0

    def predict(self, x, theta):
        z = np.dot(self.W, x) - theta
        z = round(z, 2)
        return self.activation_fn(z)

    def fit(self, X, d, theta):
        count = 1

        for _ in range(self.epochs):
            print("Epoch:", count)

            for i in range(len(d)):
                x = X[i]
                print("Input:", x, "\tWeight:", self.W)

                y = self.predict(x, theta)
                e = d[i] - y
                self.W = self.W + self.lr * e * x

            count += 1

X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

d = np.array([0, 0, 0, 1])

theta = 0.4

perceptron = Perceptron(input_size=2)
perceptron.fit(X, d, theta)

print("\nFinal Weights:", perceptron.W)

print("\nAND Gate Output")
for x in X:
    print(x, "->", perceptron.predict(x, theta))

Epoch: 1
Input: [0 0] 	Weight: [ 0.3 -0.2]
Input: [0 1] 	Weight: [ 0.3 -0.2]
Input: [1 0] 	Weight: [ 0.3 -0.2]
Input: [1 1] 	Weight: [ 0.3 -0.2]
Epoch: 2
Input: [0 0] 	Weight: [0.5 0. ]
Input: [0 1] 	Weight: [0.5 0. ]
Input: [1 0] 	Weight: [0.5 0. ]
Input: [1 1] 	Weight: [0.3 0. ]
Epoch: 3
Input: [0 0] 	Weight: [0.5 0.2]
Input: [0 1] 	Weight: [0.5 0.2]
Input: [1 0] 	Weight: [0.5 0.2]
Input: [1 1] 	Weight: [0.3 0.2]
Epoch: 4
Input: [0 0] 	Weight: [0.3 0.2]
Input: [0 1] 	Weight: [0.3 0.2]
Input: [1 0] 	Weight: [0.3 0.2]
Input: [1 1] 	Weight: [0.3 0.2]

Final Weights: [0.3 0.2]

AND Gate Output
[0 0] -> 0
[0 1] -> 0
[1 0] -> 0
[1 1] -> 1


In [4]:
import numpy as np


def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

def check_error(predicted_output):
    expected_output = np.array([[0], [1], [1], [0]])

    for i, j in zip(expected_output, predicted_output):
        if abs(i[0] - j[0]) > 0.001:
            return True

    return False


inputs = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

expected_output = np.array([
    [0],
    [1],
    [1],
    [0]
])

lr = 0.1

epoch = 0

max_epochs = 100000

inputLayerNeurons = int(input("Enter no of input layer: "))
hiddenLayerNeurons = int(input("Enter no of hidden layer: "))
outputLayerNeurons = int(input("Enter no of output layer: "))

hidden_weights = []

for i in range(1, inputLayerNeurons + 1):

    hidden_weights_ind = []

    for j in range(
        inputLayerNeurons + 1,
        inputLayerNeurons + hiddenLayerNeurons + 1
    ):

        weight = float(input("w" + str(i) + str(j) + ": "))
        hidden_weights_ind.append(weight)

    hidden_weights.append(hidden_weights_ind)

output_weights = []

for i in range(
    inputLayerNeurons + 1,
    inputLayerNeurons + hiddenLayerNeurons + 1
):

    output_weights_ind = []

    for j in range(
        inputLayerNeurons + hiddenLayerNeurons + 1,
        inputLayerNeurons + hiddenLayerNeurons + outputLayerNeurons + 1
    ):

        weight = float(input("w" + str(i) + str(j) + ": "))
        output_weights_ind.append(weight)

    output_weights.append(output_weights_ind)


hidden_bias = []
output_bias = []

for i in range(
    inputLayerNeurons + 1,
    inputLayerNeurons + hiddenLayerNeurons + outputLayerNeurons + 1
):

    if i > inputLayerNeurons + hiddenLayerNeurons:

        bias = float(input("o" + str(i) + ": "))
        output_bias.append(bias)

    else:

        bias = float(input("o" + str(i) + ": "))
        hidden_bias.append(bias)


hidden_weights = np.asarray(hidden_weights, dtype=float)
hidden_bias = np.asarray([hidden_bias], dtype=float)

output_weights = np.asarray(output_weights, dtype=float)
output_bias = np.asarray([output_bias], dtype=float)


print("\nInitial hidden weights:")
print(hidden_weights)

print("\nInitial hidden biases:")
print(hidden_bias)

print("\nInitial output weights:")
print(output_weights)

print("\nInitial output biases:")
print(output_bias)


predicted_output = np.zeros((4, 1))


while check_error(predicted_output) and epoch < max_epochs:

    epoch += 1

    hidden_layer_activation = np.dot(
        inputs,
        hidden_weights
    )

    hidden_layer_activation += hidden_bias

    hidden_layer_output = sigmoid(
        hidden_layer_activation
    )


    output_layer_activation = np.dot(
        hidden_layer_output,
        output_weights
    )

    output_layer_activation += output_bias

    predicted_output = sigmoid(
        output_layer_activation
    )


    error = expected_output - predicted_output

    d_predicted_output = (
        error *
        sigmoid_derivative(predicted_output)
    )


    error_hidden_layer = np.dot(
        d_predicted_output,
        output_weights.T
    )

    d_hidden_layer = (
        error_hidden_layer *
        sigmoid_derivative(hidden_layer_output)
    )


    output_weights += (
        np.dot(
            hidden_layer_output.T,
            d_predicted_output
        ) * lr
    )

    output_bias += (
        np.sum(
            d_predicted_output,
            axis=0,
            keepdims=True
        ) * lr
    )


    hidden_weights += (
        np.dot(
            inputs.T,
            d_hidden_layer
        ) * lr
    )

    hidden_bias += (
        np.sum(
            d_hidden_layer,
            axis=0,
            keepdims=True
        ) * lr
    )


print("\nFinal hidden weights:")
print(hidden_weights)

print("\nFinal hidden bias:")
print(hidden_bias)

print("\nFinal output weights:")
print(output_weights)

print("\nFinal output bias:")
print(output_bias)


print("\nOutput from neural network:")

for output in predicted_output:
    print(output)


print("\nNo of epochs:")
print(epoch)


print("\nXOR Result:")

for output in predicted_output:

    if output[0] >= 0.5:
        print(1)
    else:
        print(0)

Enter no of input layer:  2
Enter no of hidden layer:  2
Enter no of output layer:  1
w13:  3
w14:  6
w23:  4
w24:  5
w35:  2
w45:  4
o3:  1
o4:  6
o5:  3.93



Initial hidden weights:
[[3. 6.]
 [4. 5.]]

Initial hidden biases:
[[1. 6.]]

Initial output weights:
[[2.]
 [4.]]

Initial output biases:
[[3.93]]

Final hidden weights:
[[9.01236344 5.99210583]
 [9.0160955  4.97822349]]

Final hidden bias:
[[-1.01794617  6.01768368]]

Final output weights:
[[ 6.53572699]
 [-2.85480911]]

Final output bias:
[[-2.9870496]]

Output from neural network:
[0.01630005]
[0.66634951]
[0.66634091]
[0.66682686]

No of epochs:
100000

XOR Result:
0
1
1
1


In [ ]:
import numpy as np


# Sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))


# Derivative of sigmoid
def sigmoid_derivative(x):
    return x * (1 - x)


# Check whether the output is close to expected output
def check_error(predicted_output):
    expected_output = np.array([[0], [1], [1], [0]])

    for i, j in zip(expected_output, predicted_output):
        if abs(i[0] - j[0]) > 0.001:
            return True

    return False


# --------------------------------------------------
# Input dataset for XOR
# --------------------------------------------------

inputs = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

expected_output = np.array([
    [0],
    [1],
    [1],
    [0]
])


# Learning rate
lr = 0.1

# Epoch counter
epoch = 0

# Maximum number of epochs
max_epochs = 100000


# --------------------------------------------------
# Number of neurons
# --------------------------------------------------

inputLayerNeurons = int(input("Enter no of input layer: "))
hiddenLayerNeurons = int(input("Enter no of hidden layer: "))
outputLayerNeurons = int(input("Enter no of output layer: "))


# --------------------------------------------------
# Hidden layer weights
# --------------------------------------------------

hidden_weights = []

for i in range(1, inputLayerNeurons + 1):

    hidden_weights_ind = []

    for j in range(
        inputLayerNeurons + 1,
        inputLayerNeurons + hiddenLayerNeurons + 1
    ):

        weight = float(input("w" + str(i) + str(j) + ": "))
        hidden_weights_ind.append(weight)

    hidden_weights.append(hidden_weights_ind)


# --------------------------------------------------
# Output layer weights
# --------------------------------------------------

output_weights = []

for i in range(
    inputLayerNeurons + 1,
    inputLayerNeurons + hiddenLayerNeurons + 1
):

    output_weights_ind = []

    for j in range(
        inputLayerNeurons + hiddenLayerNeurons + 1,
        inputLayerNeurons + hiddenLayerNeurons + outputLayerNeurons + 1
    ):

        weight = float(input("w" + str(i) + str(j) + ": "))
        output_weights_ind.append(weight)

    output_weights.append(output_weights_ind)


# --------------------------------------------------
# Bias values
# --------------------------------------------------

hidden_bias = []
output_bias = []

for i in range(
    inputLayerNeurons + 1,
    inputLayerNeurons + hiddenLayerNeurons + outputLayerNeurons + 1
):

    if i > inputLayerNeurons + hiddenLayerNeurons:

        bias = float(input("o" + str(i) + ": "))
        output_bias.append(bias)

    else:

        bias = float(input("o" + str(i) + ": "))
        hidden_bias.append(bias)


# Convert to NumPy arrays

hidden_weights = np.asarray(hidden_weights, dtype=float)
hidden_bias = np.asarray([hidden_bias], dtype=float)

output_weights = np.asarray(output_weights, dtype=float)
output_bias = np.asarray([output_bias], dtype=float)


# --------------------------------------------------
# Print initial values
# --------------------------------------------------

print("\nInitial hidden weights:")
print(hidden_weights)

print("\nInitial hidden biases:")
print(hidden_bias)

print("\nInitial output weights:")
print(output_weights)

print("\nInitial output biases:")
print(output_bias)


# Initial predicted output

predicted_output = np.zeros((4, 1))


# --------------------------------------------------
# Training
# --------------------------------------------------

while check_error(predicted_output) and epoch < max_epochs:

    epoch += 1

    # ----------------------------------------------
    # Forward Propagation
    # ----------------------------------------------

    hidden_layer_activation = np.dot(
        inputs,
        hidden_weights
    )

    hidden_layer_activation += hidden_bias

    hidden_layer_output = sigmoid(
        hidden_layer_activation
    )


    output_layer_activation = np.dot(
        hidden_layer_output,
        output_weights
    )

    output_layer_activation += output_bias

    predicted_output = sigmoid(
        output_layer_activation
    )


    # ----------------------------------------------
    # Backpropagation
    # ----------------------------------------------

    error = expected_output - predicted_output

    d_predicted_output = (
        error *
        sigmoid_derivative(predicted_output)
    )


    error_hidden_layer = np.dot(
        d_predicted_output,
        output_weights.T
    )

    d_hidden_layer = (
        error_hidden_layer *
        sigmoid_derivative(hidden_layer_output)
    )


    # ----------------------------------------------
    # Update weights and biases
    # ----------------------------------------------

    output_weights += (
        np.dot(
            hidden_layer_output.T,
            d_predicted_output
        ) * lr
    )

    output_bias += (
        np.sum(
            d_predicted_output,
            axis=0,
            keepdims=True
        ) * lr
    )


    hidden_weights += (
        np.dot(
            inputs.T,
            d_hidden_layer
        ) * lr
    )

    hidden_bias += (
        np.sum(
            d_hidden_layer,
            axis=0,
            keepdims=True
        ) * lr
    )


# --------------------------------------------------
# Final values
# --------------------------------------------------

print("\nFinal hidden weights:")
print(hidden_weights)

print("\nFinal hidden bias:")
print(hidden_bias)

print("\nFinal output weights:")
print(output_weights)

print("\nFinal output bias:")
print(output_bias)


# --------------------------------------------------
# Final output
# --------------------------------------------------

print("\nOutput from neural network:")

for output in predicted_output:
    print(output)


print("\nNo of epochs:")
print(epoch)


# --------------------------------------------------
# XOR classification
# --------------------------------------------------

print("\nXOR Result:")

for output in predicted_output:

    if output[0] >= 0.5:
        print(1)
    else:
        print(0)