In [1]:
import numpy as np
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [2]:
print(type(x))
print(x.shape)
print(x.size)
print(x.dtype)

<class 'numpy.ndarray'>
(5,)
5
int32


In [3]:
print(np.arange(1,10,5))

[1 6]


In [4]:
print(np.linspace(1,10,5))

[ 1.    3.25  5.5   7.75 10.  ]


In [5]:
x = np.array([1,2,3,4,5,6])
print(x.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [6]:
print(np.zeros((2,3)))
print(np.ones((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [7]:
print(np.random.randint(0,10,5))

[0 5 7 9 2]


In [8]:
a = np.arange(15)
print(a[3:9:2])

[3 5 7]


In [9]:
x = np.array([1,2,3,4,5,6])
y = np.array([5,6,7,8,9,10])

print(x+y)
print(x-y)
print(x*y)
print(x/y)

[ 6  8 10 12 14 16]
[-4 -4 -4 -4 -4 -4]
[ 5 12 21 32 45 60]
[0.2        0.33333333 0.42857143 0.5        0.55555556 0.6       ]


In [10]:
x = np.array([1,2,3,4,5,6])

print(x.sum())
print(x.mean())
print(x.min())
print(x.max())
print(x.var())
print(x.std())

21
3.5
1
6
2.9166666666666665
1.707825127659933


In [11]:
x = np.array([[2,3],[6,7]])
y = np.array([[5,6],[8,7]])

print(np.add(x,y))

[[ 7  9]
 [14 14]]


In [12]:
a = np.arange(15).reshape(3,5)
print(a.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [15]:
print(a.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
