In [3]:
import pandas as pd
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

# Reading the csv Iris dataset file
df = pd.read_csv("iris1.csv")

print(df.head(10))

# Conditioning the data
array = df.values
X = array[:, 0:4]
y = array[:, 4]

# Condition the training and Testing data
# The number of samples can be tuned with the test_size parameter.
# Here, 95% of the data is used.
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.95, random_state=0
)

# Construct the Linear model
model = SVC(kernel='linear', random_state=0)

model.fit(X_train, y_train)

# Test the model with Linear kernel
pred = model.predict(X_test)

# Prepare confusion matrix
print("\n\nThe confusion matrix is \n\n")
conf = confusion_matrix(y_test, pred)
print(conf)

# Prepare Classification Report
print("\n\nAccuracy is")
accuracy = accuracy_score(y_test, pred)
print(accuracy)

# Or report can be obtained as follows
print('\n Classification Report')
report = classification_report(y_test, pred)
print(report)

# RBF kernel
model1 = SVC(kernel='rbf', random_state=0)

model1.fit(X_train, y_train)

# Test the model
pred = model1.predict(X_test)

# Prepare confusion matrix
print("\n\nThe confusion matrix for RBF kernel is \n\n")
conf = confusion_matrix(y_test, pred)
print(conf)

# Prepare Classification Report
print("\n\nAccuracy for RBF kernel is")
accuracy = accuracy_score(y_test, pred)
print(accuracy)

   SepalLength  SepalWidth  PetalLength  PetalWidth      Species
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa
5          5.4         3.9          1.7         0.4  Iris-setosa
6          4.6         3.4          1.4         0.3  Iris-setosa
7          5.0         3.4          1.5         0.2  Iris-setosa
8          4.4         2.9          1.4         0.2  Iris-setosa
9          4.9         3.1          1.5         0.1  Iris-setosa


The confusion matrix is 


[[46  0  0]
 [ 0 40  9]
 [ 0  1 47]]


Accuracy is
0.9300699300699301

 Classification Report
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        46
Iris-versicolor       0.98      0.82      0.89 

In [1]:
import numpy
print(numpy.__version__)
print(numpy.__file__)

1.26.4
C:\ProgramData\anaconda3\Lib\site-packages\numpy\__init__.py
